"""Export exp25 L=128 decomposition table to LaTeX."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

_FILLERS = (
    "prose",
    "varied_prose",
    "coherent_passage",
    "relation_noise",
    "relation_noise_false",
    "passage_shuffled",
    "passage_scrambled",
    "coherent_full",
)
_CATEGORIES = (
    "World Capital",
    "Athlete Sport",
    "Book Author",
    "Company Headquarter",
    "Company Founder",
    "Official Language",
)
_SIZES = ("2.8b", "12b")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary-json", type=str, required=True)
    parser.add_argument("--output-tex", type=str, required=True)
    parser.add_argument("--metric", choices=("gen", "lp"), default="gen")
    args = parser.parse_args()

    with open(args.summary_json, encoding="utf-8") as f:
        data = json.load(f)
    rows = [r for r in data.get("rows", []) if r.get("kind") == "sweep"]

    def lookup(size: str, cat: str, filler: str) -> str:
        if filler == "coherent_full":
            for L in (-1, 0):
                for r in rows:
                    if (
                        r.get("size") == size
                        and r.get("category") == cat
                        and r.get("filler_kind") == filler
                        and r.get("length") == L
                    ):
                        return f"{r['p_in_context']:.2f}"
            return "--"
        for r in rows:
            if (
                r.get("size") == size
                and r.get("category") == cat
                and r.get("filler_kind") == filler
                and r.get("length") == 128
            ):
                return f"{r['p_in_context']:.2f}"
        return "--"

    lines = [
        "% Auto-generated by scripts/export_coherent_decomp_tex.py",
        "\\begin{table*}[t]",
        "  \\centering",
        "  \\footnotesize",
        "  \\setlength{\\tabcolsep}{3pt}",
        "  \\caption{$P(\\text{in-context})$ at $L{=}128$ on ParaConflict "
        f"({args.metric} classifier). "
        "\\texttt{coherent\\_full} uses the native dataset passage.}",
        "  \\label{tab:coherent-decomp-L128}",
        "  \\begin{tabular}{@{}l" + "c" * len(_FILLERS) + "@{}}",
        "    \\toprule",
        " Category & "
        + " & ".join("\\texttt{" + f.replace("_", "\\_") + "}" for f in _FILLERS)
        + " \\\\",
        "    \\midrule",
    ]
    for size in _SIZES:
        lines.append(f"    \\multicolumn{{{len(_FILLERS)+1}}}{{l}}{{\\textbf{{Pythia-{size}}}}} \\\\")
        for cat in _CATEGORIES:
            cells = [lookup(size, cat, f) for f in _FILLERS]
            lines.append(f"    {cat.replace(' ', '~')} & " + " & ".join(cells) + " \\\\")
        lines.append("    \\addlinespace")
    lines.extend(["    \\bottomrule", "  \\end{tabular}", "\\end{table*}"])

    out = Path(args.output_tex)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
