"""Export ParaConflict mean wordfreq table for the paper appendix."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

_CATEGORIES = (
    "World Capital",
    "Athlete Sport",
    "Book Author",
    "Company Headquarter",
    "Company Founder",
    "Official Language",
)
_ROLE_ORDER = ("subjects", "memorized_answers", "distractors")


def _category_tex(category: str) -> str:
    return category.replace(" ", "~")


def _fmt_zipf(value: float) -> str:
    return f"{value:.2f}"


def _role_cells(summary: dict, role: str) -> str:
    stats = summary.get(role)
    if not stats:
        return "-- & --"
    return f"{stats['n']} & {_fmt_zipf(stats['zipf_mean'])}"


def render_summary_table(payload: dict) -> str:
    summary = payload["_meta"]["summary"]
    lines = [
        r"% Auto-generated by scripts/export_paraconflict_freq_appendix_tex.py",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \small",
        r"  \setlength{\tabcolsep}{4pt}",
        r"  \caption{Mean \texttt{wordfreq} Zipf score per unique entity in each "
        r"ParaConflict relation category. "
        r"For each role we average Zipf over all distinct strings of that type "
        r"(subjects, memorized answers, distractors). "
        r"Leading articles (\texttt{the}) are stripped before scoring.}",
        r"  \label{tab:paraconflict-freq-summary}",
        r"  \begin{tabular}{@{}lrrrrrr@{}}",
        r"    \toprule",
        r"    & \multicolumn{2}{c}{Subject} & \multicolumn{2}{c}{Memorized answer} "
        r"& \multicolumn{2}{c}{Distractor} \\",
        r"    \cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}",
        r"    Category & $n$ & $\bar{z}$ & $n$ & $\bar{z}$ & $n$ & $\bar{z}$ \\",
        r"    \midrule",
    ]
    for category in _CATEGORIES:
        if category not in summary:
            continue
        cat_summary = summary[category]
        subj = _role_cells(cat_summary, "subjects")
        mem = _role_cells(cat_summary, "memorized_answers")
        dist = _role_cells(cat_summary, "distractors")
        lines.append(
            f"    {_category_tex(category)} & {subj} & {mem} & {dist} \\\\"
        )
    lines.extend(
        [
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--frequency-json", type=str, required=True)
    parser.add_argument(
        "--output-tex",
        type=str,
        default="paper/tables/paraconflict_entity_frequency.tex",
    )
    args = parser.parse_args()

    payload = json.loads(Path(args.frequency_json).read_text(encoding="utf-8"))
    tex = render_summary_table(payload)

    out = Path(args.output_tex)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tex, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
