"""Export exp24 country-frequency hypothesis results to LaTeX table fragments."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


_VERDICT_TEX = {
    "supports": r"\textbf{supports}",
    "weak_support": "weak support",
    "flat": "flat",
    "weak_inverts": "weak invert",
    "inverts": r"\textbf{inverts}",
    "insufficient_data": "n/a",
}


def _pct(x: float) -> str:
    return f"{100.0 * x:.1f}"


def _rho(x: float) -> str:
    if x != x:  # NaN
        return "---"
    return f"{x:+.3f}"


def _delta(x: float) -> str:
    if x != x:
        return "---"
    return f"{100.0 * x:+.1f}"


def _model_label(label: str) -> str:
    mapping = {
        "gpt2": "GPT-2 small",
        "gpt2-medium": "GPT-2 medium",
        "gpt2-large": "GPT-2 large",
        "gpt2-xl": "GPT-2 XL",
    }
    if label in mapping:
        return mapping[label]
    if label.startswith("pythia-"):
        return f"Pythia-{label.split('-', 1)[1]}"
    if label.startswith("qwen3-base-"):
        return f"Qwen3-Base-{label.split('-', 2)[2]}"
    if label.startswith("qwen3-"):
        return f"Qwen3-{label.split('-', 1)[1]}"
    if label.startswith("ministral3-"):
        parts = label.split("-", 2)
        variant = parts[1].capitalize()
        return f"Ministral-3 {variant}-{parts[2]}"
    return label


def render_table(summary_path: Path) -> str:
    data = json.loads(summary_path.read_text(encoding="utf-8"))
    n_bins = data["n_bins"]
    bin_headers = [f"Q{int(round(100 * (i + 1) / n_bins))}" for i in range(n_bins)]
    n_per_bin = int(round(47299 / n_bins))
    models = sorted(
        data["models"],
        key=lambda m: (m["family"], m.get("params_b") or 0),
    )

    caption = (
        rf"  \caption{{Generative $P(\text{{memorized}})$ by queried-country "
        rf"\texttt{{wordfreq}} Zipf percentile bin ({n_bins} equal-count bins; "
        rf"$n{{\approx}}{n_per_bin:,}$ prompts per bin per model).  "
        r"$\rho$: Spearman correlation between per-country \texttt{wordfreq} Zipf and "
        r"$P(\text{memorized})$ (218 countries); "
        r"$\rho_{\mathrm{bin}}$: Spearman across decile bins (diagnostic).  "
        r"$\Delta$: $P(\text{memorized})$ in the highest minus lowest bin (percentage points).  "
        r"Verdicts follow \S\ref{sec:results-country-freq}: "
        r"\emph{supports} if $\rho \geq 0.3$ and $\Delta \geq 5$\,pp.}"
    )
    lines = [
        r"% Auto-generated by scripts/export_country_freq_appendix_tex.py",
        r"\begin{table*}[t]",
        r"  \centering",
        r"  \scriptsize",
        r"  \setlength{\tabcolsep}{2.5pt}",
        caption,
        r"  \label{tab:country-freq-mem}",
        r"  \begin{tabular}{@{}l" + "r" * n_bins + r"rrrl@{}}",
        r"    \toprule",
        "    Model & "
        + " & ".join(bin_headers)
        + r" & $\rho$ & $\rho_{\mathrm{bin}}$ & $\Delta$\,pp & Verdict \\",
        r"    \midrule",
    ]

    for m in models:
        p_bins = [_pct(x) for x in m["p_memorized_by_bin"]]
        verdict = _VERDICT_TEX.get(m["verdict"], m["verdict"])
        lines.append(
            f"    {_model_label(m['label'])} & "
            + " & ".join(p_bins)
            + f" & {_rho(m['spearman_rho'])} & {_rho(m.get('spearman_rho_bins', float('nan')))} "
            + f"& {_delta(m['delta_p_memorized'])} & {verdict} \\\\"
        )

    lines.extend(
        [
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary-json",
        type=Path,
        default=Path("summaries/country_freq_mem_hypothesis_summary.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("paper/tables/country_freq_mem_hypothesis.tex"),
    )
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    tex = render_table(args.summary_json)
    args.output.write_text(tex, encoding="utf-8")
    print(f"Wrote {args.output}")

    tables_output = Path("tables") / args.output.name
    tables_output.parent.mkdir(parents=True, exist_ok=True)
    tables_output.write_text(tex, encoding="utf-8")
    print(f"Wrote {tables_output}")


if __name__ == "__main__":
    main()
